# Generated by Django 4.1.7 on 2023-07-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_categoriaforo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaforo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='categoria_imagenes/'),
        ),
    ]
