# Generated by Django 4.1.7 on 2023-07-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_fecha_de_creacion_categoriaforo_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaforo',
            options={'permissions': [('crear_categoriaforo', 'Puede agregar categoría de foro'), ('editar_categoriaforo', 'Puede agregar categoría de foro'), ('eliminar_categoriaforo', 'Puede eliminar categoría de foro')]},
        ),
    ]
